### ISSUE TITLE
enable touch to click and palm detect by default

### ISSUE THREAD

**Issue by csmart** [kororaproject/kp-kde-settings#3]
we should enable touch to click for touchpads in KDE by default

**Comment by mustafa-muhammad** [comment]
I think it belongs to kde-settings it has files like:
/usr/share/kde-settings/kde-profile/default/share/config/konsolerc
and others to set the default configurations
I think we should put:
/usr/share/kde-settings/kde-profile/default/share/config/touchpadrc
With at least:

[parameters]
CircScrollDelta=5.73
HorizScrollDelta=2.3
MaxTapMove=2.8
OneFingerTapButton=LeftButton
VertScrollDelta=1.5

I added a new user and enabling left finger by single tap, you can add what you prefer.

**Comment by csmart** [comment]
pushed kde-settings.noarch 1:21-2.fc21.2 to testing repo

**Comment by csmart** [comment]
pushed to stable, thanks!
